version: 2.1

jobs:
  build:
    docker:
     - image: circleci/node:12.16
    steps:
     - checkout
     - run: echo "build project"
     - run: npm install
     - run: npm run build
workflows:
  build-project:
    jobs:
    - build
        