version: 2.1

jobs:
  build:
    docker:
     - image: circleci/node:12.16
    steps:
     - checkout
     - run: echo "build project"
     - run: npm install
  deploy:
    docker:
      - image: circleci/node:12.16
        
    steps:
      - checkout
      - run: my-deploy-commands
   
workflows:
  build-project:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
        